version: "3.7"

services:
  cogsrv:
    image: cogsrv
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "./code:/home/jovyan/code"
      - "./data:/home/jovyan/data"
    env_file:
      - cs.env
    command: ./entrypoint.sh

